import { Student } from "@/types";

// Dummy Data
const students: Student[] = [
  {
    id: 1,
    firstname: "Khalid",
    lastname: "Olatunji",
    othername: "Abdulmalik",
    abbreviation: "KO",
    username: "CL123456",
    dateOfBirth: "2009-05-15",
    dateRegistered: "2022-02-15",
    gender: "Male",
    status: "Active",
    previousSchoolAttended: "Ikeja High School",
    currentClass: {
      name: "SSS 1",
      division: "A",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O+",
      genotype: "AA",
      allergies: ["Peanuts", "Penicillin"],
      medicalHistory: ["Asthma", "Sickle cell"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "123 Main Street",
      stateOfResidence: "Lagos State",
      lgaOfHouse: "Ikeja",
    },
    origin: {
      stateOfOrigin: "Lagos State",
      lgaOfOrigin: "Ikeja",
    },
    guardians: [
      {
        firstname: "Adekunle",
        lastname: "Olatunji",
        othername: "Adeyemi",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Aderonke",
        lastname: "Olatunji",
        othername: "Adeyemi",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
  },
  {
    id: 2,
    firstname: "Michael",
    lastname: "Johnson",
    othername: "Oluwatobiloba",
    abbreviation: "MJ",
    username: "CL128553",
    dateOfBirth: "2008-01-20",
    dateRegistered: "2022-01-01",
    gender: "Male",
    status: "Inactive",
    previousSchoolAttended: "Lagos Academy",
    currentClass: {
      name: "SSS 2",
      division: "B",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "B+",
      genotype: "AA",
      allergies: ["Bee sting", "Qiwi"],
      medicalHistory: ["Asthma"],
      currentMedications: null,
    },
    address: {
      houseAddress: "456 Elm Street",
      stateOfResidence: "Lagos State",
      lgaOfHouse: "Ikeja",
    },
    origin: {
      stateOfOrigin: "Lagos State",
      lgaOfOrigin: "Ikeja",
    },
    guardians: [
      {
        firstname: "Adeyemi",
        lastname: "Johnson",
        othername: "Adeyemi",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
    ],
  },
  {
    id: 3,
    firstname: "David",
    lastname: "Chibueke",
    othername: "Emeka",
    abbreviation: "DC",
    username: "CL129876",
    dateOfBirth: "2010-08-12",
    dateRegistered: "2022-03-12",
    gender: "Male",
    status: "Graduated",
    previousSchoolAttended: null,
    currentClass: {
      name: "JSS 2",
      division: "C",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O-",
      genotype: "AA",
      allergies: ["Peanuts", "Penicillin"],
      medicalHistory: ["Asthma"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "789 Pine Street",
      stateOfResidence: "Lagos State",
      lgaOfHouse: "Ikeja",
    },
    origin: {
      stateOfOrigin: "Kwara State",
      lgaOfOrigin: "Ilorin-West",
    },
    guardians: [
      {
        firstname: "Chijioke",
        lastname: "Chibueke",
        othername: "Adeyemi",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Stella",
        lastname: "Chibueke",
        othername: "Adeyemi",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
  },
  {
    id: 4,
    firstname: "Sarah",
    lastname: "Christopher",
    othername: "Mary",
    abbreviation: "SC",
    username: "CL127890",
    dateOfBirth: "2011-10-25",
    dateRegistered: "2022-04-25",
    gender: "Female",
    status: "Active",
    previousSchoolAttended: "Lagos Girls School",
    currentClass: {
      name: "JSS 2",
      division: "C",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O+",
      genotype: "AA",
      allergies: ["Peanuts", "Penicillin"],
      medicalHistory: ["Asthma"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "321 Oak Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    origin: {
      stateOfOrigin: "Anambra State",
      lgaOfOrigin: "Anambra-West",
    },
    guardians: [
      {
        firstname: "Chijioke",
        lastname: "Chibueke",
        othername: "Adeyemi",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Stella",
        lastname: "Chibueke",
        othername: "Adeyemi",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
  },
  {
    id: 5,
    firstname: "Jessica",
    lastname: "Williams",
    othername: "Anne",
    abbreviation: "JW",
    username: "CL125678",
    dateOfBirth: "2007-11-30",
    dateRegistered: "2022-05-10",
    gender: "Female",
    status: "Active",
    previousSchoolAttended: "Ikeja International School",
    currentClass: {
      name: "SSS 3",
      division: null,
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O+",
      genotype: "AA",
      allergies: ["Peanuts", "Penicillin"],
      medicalHistory: ["Asthma"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "654 Maple Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "James",
        lastname: "Williams",
        othername: "Adeyemi",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Jane",
        lastname: "Williams",
        othername: "Adeyemi",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Bayelsa State",
      lgaOfOrigin: "Idiom-South",
    },
  },
  {
    id: 6,
    firstname: "Daniel",
    lastname: "Smith",
    othername: "James",
    abbreviation: "DS",
    username: "CL124567",
    dateOfBirth: "2012-03-22",
    dateRegistered: "2022-06-15",
    gender: "Male",
    status: "Active",
    previousSchoolAttended: "Ikeja Primary School",
    currentClass: {
      name: "JSS 1",
      division: "A",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O+",
      genotype: "AA",
      allergies: ["Peanuts", "Penicillin"],
      medicalHistory: ["Asthma"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "987 Cedar Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Adetola",
        lastname: "Smith",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
    ],
    origin: {
      stateOfOrigin: "Taraba State",
      lgaOfOrigin: "Idiroko LGA",
    },
  },
  {
    id: 7,
    firstname: "Emily",
    lastname: "Brown",
    othername: "Grace",
    abbreviation: "EB",
    username: "CL123789",
    dateOfBirth: "2008-07-19",
    dateRegistered: "2022-07-20",
    gender: "Female",
    status: "Active",
    previousSchoolAttended: "Ikeja Academy",
    currentClass: {
      name: "SSS 2",
      division: "B",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O+",
      genotype: "AA",
      allergies: ["Peanuts", "Penicillin"],
      medicalHistory: ["Asthma"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "135 Birch Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "John",
        lastname: "Brown",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Grace",
        lastname: "Brown",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Lagos State",
      lgaOfOrigin: "Eti-Osa",
    },
  },
  {
    id: 8,
    firstname: "Joshua",
    lastname: "Taylor",
    othername: "Michael",
    abbreviation: "JT",
    username: "CL126789",
    dateOfBirth: "2010-12-05",
    dateRegistered: "2022-08-25",
    gender: "Male",
    status: "Active",
    previousSchoolAttended: "Ikeja Secondary School",
    currentClass: {
      name: "Nursery 1",
      division: "Courage",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O+",
      genotype: "AA",
      allergies: ["Peanuts", "Penicillin"],
      medicalHistory: ["Asthma"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "246 Spruce Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Michael",
        lastname: "Taylor",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Joshua",
        lastname: "Taylor",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Anambra State",
      lgaOfOrigin: "Anambra-West",
    },
  },
  {
    id: 9,
    firstname: "Sophia",
    lastname: "Johnson",
    othername: "Marie",
    abbreviation: "SJ",
    username: "CL128901",
    dateOfBirth: "2009-09-15",
    dateRegistered: "2022-09-30",
    gender: "Female",
    status: "Inactive",
    previousSchoolAttended: "Ikeja Girls School",
    currentClass: {
      name: "JSS 1",
      division: "A",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O+",
      genotype: "AA",
      allergies: ["Peanuts", "Penicillin"],
      medicalHistory: ["Asthma"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "369 Willow Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Alexander",
        lastname: "Johnson",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Marie",
        lastname: "Johnson",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Kogi State",
      lgaOfOrigin: "Kaba",
    },
  },
  {
    id: 10,
    firstname: "Ethan",
    lastname: "Davis",
    othername: "Alexander",
    abbreviation: "ED",
    username: "CL129012",
    dateOfBirth: "2011-05-10",
    dateRegistered: "2022-10-15",
    gender: "Male",
    status: "Active",
    previousSchoolAttended: "Ikeja Academy",
    currentClass: {
      name: "JSS 2",
      division: "B",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O+",
      genotype: "AA",
      allergies: ["Peanuts", "Penicillin"],
      medicalHistory: ["Asthma"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "159 Elm Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Alexander",
        lastname: "Davis",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Isabella",
        lastname: "Martinez",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Lagos State",
      lgaOfOrigin: "Epe",
    },
  },
  {
    id: 11,
    firstname: "Olivia",
    lastname: "Martinez",
    othername: "Isabella",
    abbreviation: "OM",
    username: "CL130123",
    dateOfBirth: "2007-02-25",
    dateRegistered: "2022-11-05",
    gender: "Female",
    status: "Graduated",
    previousSchoolAttended: "Ikeja International School",
    currentClass: {
      name: "SSS 3",
      division: null,
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O+",
      genotype: "AA",
      allergies: ["Peanuts", "Penicillin"],
      medicalHistory: ["Asthma"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "753 Pine Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Olivia",
        lastname: "Martinez",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Liam",
        lastname: "Garcia",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Ekiti State",
      lgaOfOrigin: "Ado-Ekiti",
    },
  },
  {
    id: 12,
    firstname: "Liam",
    lastname: "Garcia",
    othername: "Benjamin",
    abbreviation: "LG",
    username: "CL131234",
    dateOfBirth: "2012-08-30",
    dateRegistered: "2022-12-20",
    gender: "Male",
    status: "Active",
    previousSchoolAttended: "Ikeja Primary School",
    currentClass: {
      name: "JSS 1",
      division: "A",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O+",
      genotype: "AA",
      allergies: ["Peanuts", "Penicillin"],
      medicalHistory: ["Asthma"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "852 Cedar Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Liam",
        lastname: "Garcia",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
    ],
    origin: {
      stateOfOrigin: "Lagos State",
      lgaOfOrigin: "Ikeja",
    },
  },
  {
    id: 13,
    firstname: "Ava",
    lastname: "Rodriguez",
    othername: "Sophia",
    abbreviation: "AR",
    username: "CL132345",
    dateOfBirth: "2008-11-15",
    dateRegistered: "2023-01-10",
    gender: "Female",
    status: "Active",
    previousSchoolAttended: "Ikeja Academy",
    currentClass: {
      name: "SSS 2",
      division: "A",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O+",
      genotype: "AA",
      allergies: ["Peanuts", "Penicillin"],
      medicalHistory: ["Asthma"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "963 Maple Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Ava",
        lastname: "Rodriguez",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Ogun State",
      lgaOfOrigin: "Ijebu",
    },
  },
  {
    id: 14,
    firstname: "Sophia",
    lastname: "Wilson",
    othername: "Grace",
    abbreviation: "SW",
    username: "CL133456",
    dateOfBirth: "2009-03-22",
    dateRegistered: "2023-02-15",
    gender: "Female",
    status: "Inactive",
    previousSchoolAttended: "Ikeja Girls School",
    currentClass: {
      name: "SSS 1",
      division: "B",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O+",
      genotype: "AA",
      allergies: ["Peanuts", "Penicillin"],
      medicalHistory: ["Asthma"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "147 Birch Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Grace",
        lastname: "Wilson",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Imo State",
      lgaOfOrigin: "Onuaha LGA",
    },
  },
  {
    id: 15,
    firstname: "James",
    lastname: "Anderson",
    othername: "Michael",
    abbreviation: "JA",
    username: "CL134567",
    dateOfBirth: "2010-07-18",
    dateRegistered: "2023-03-05",
    gender: "Male",
    status: "Graduated",
    previousSchoolAttended: "Ikeja Secondary School",
    currentClass: {
      name: "JSS 3",
      division: null,
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O+",
      genotype: "AA",
      allergies: ["Peanuts", "Penicillin"],
      medicalHistory: ["Asthma"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "258 Spruce Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "James",
        lastname: "Anderson",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Michael",
        lastname: "Anderson",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Anambra State",
      lgaOfOrigin: "Anambra-West",
    },
  },
  {
    id: 16,
    firstname: "Mia",
    lastname: "Thomas",
    othername: "Elizabeth",
    abbreviation: "MT",
    username: "CL135678",
    dateOfBirth: "2008-12-12",
    dateRegistered: "2023-04-20",
    gender: "Female",
    status: "Active",
    previousSchoolAttended: "Ikeja Academy",
    currentClass: {
      name: "SSS 2",
      division: "A",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O+",
      genotype: "AA",
      allergies: ["Peanuts", "Penicillin"],
      medicalHistory: ["Asthma"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "369 Cedar Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Mia",
        lastname: "Thomas",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Guardian",
      },
      {
        firstname: "Elizabeth",
        lastname: "Thomas",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Guardian",
      },
    ],
    origin: {
      stateOfOrigin: "Anambra State",
      lgaOfOrigin: "Anambra-West",
    },
  },
  {
    id: 17,
    firstname: "Alexander",
    lastname: "Taylor",
    othername: "James",
    abbreviation: "AT",
    username: "CL136789",
    dateOfBirth: "2011-09-05",
    dateRegistered: "2023-05-10",
    gender: "Male",
    status: "Active",
    previousSchoolAttended: "Ikeja Secondary School",
    currentClass: {
      name: "JSS 2",
      division: "A",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "B+",
      genotype: "AC",
      allergies: ["Milk", "Penicillin"],
      medicalHistory: ["Asthma"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "147 Elm Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Alexander",
        lastname: "Taylor",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "James",
        lastname: "Taylor",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Oyo State",
      lgaOfOrigin: "Ibadan-South",
    },
  },
  {
    id: 18,
    firstname: "Isabella",
    lastname: "Moore",
    othername: "Ava",
    abbreviation: "IM",
    username: "CL137890",
    dateOfBirth: "2007-04-25",
    dateRegistered: "2023-06-15",
    gender: "Female",
    status: "Inactive",
    previousSchoolAttended: "Ikeja International School",
    currentClass: {
      name: "Pre-Nursery",
      division: null,
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O+",
      genotype: "AA",
      allergies: ["Pineapple", "Fish"],
      medicalHistory: ["Asthma"],
      currentMedications: ["Inhaler"],
    },
    address: {
      houseAddress: "258 Pine Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Ava",
        lastname: "Moore",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Kano State",
      lgaOfOrigin: "Lafiagi",
    },
  },
  {
    id: 19,
    firstname: "Benjamin",
    lastname: "Jackson",
    othername: "David",
    abbreviation: "BJ",
    username: "CL138901",
    dateOfBirth: "2012-11-30",
    dateRegistered: "2023-07-20",
    gender: "Male",
    status: "Active",
    previousSchoolAttended: "Ikeja Primary School",
    currentClass: {
      name: "JSS 1",
      division: "A",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O+",
      genotype: "AA",
      allergies: ["Bee sting"],
      medicalHistory: null,
      currentMedications: ["Morphine"],
    },
    address: {
      houseAddress: "369 Maple Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Benjamin",
        lastname: "Jackson",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "David",
        lastname: "Jackson",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Kano State",
      lgaOfOrigin: "Lafiagi",
    },
  },
  {
    id: 20,
    firstname: "Emily",
    lastname: "White",
    othername: "Olivia",
    abbreviation: "EW",
    username: "CL139012",
    dateOfBirth: "2008-06-15",
    dateRegistered: "2023-08-10",
    gender: "Female",
    status: "Graduated",
    previousSchoolAttended: "Ikeja Girls School",
    currentClass: {
      name: "Nursery 2",
      division: "Courage",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "A-",
      genotype: "SS",
      allergies: ["Cat fur"],
      medicalHistory: null,
      currentMedications: null,
    },
    address: {
      houseAddress: "147 Cedar Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Daniel",
        lastname: "Harris",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Olivia",
        lastname: "White",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Ondo State",
      lgaOfOrigin: "Eti-Apa",
    },
  },
  {
    id: 21,
    firstname: "Daniel",
    lastname: "Harris",
    othername: "Michael",
    abbreviation: "DH",
    username: "CL140123",
    dateOfBirth: "2010-02-14",
    dateRegistered: "2023-09-05",
    gender: "Male",
    status: "Active",
    previousSchoolAttended: "Ikeja Academy",
    currentClass: {
      name: "JSS 3",
      division: null,
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O-",
      genotype: "AA",
      allergies: ["Kiwi"],
      medicalHistory: null,
      currentMedications: null,
    },
    address: {
      houseAddress: "258 Birch Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Daniel",
        lastname: "Harris",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Michael",
        lastname: "Harris",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Osun State",
      lgaOfOrigin: "Oshogbo",
    },
  },
  {
    id: 22,
    firstname: "Sophia",
    lastname: "Clark",
    othername: "Grace",
    abbreviation: "SC",
    username: "CL141234",
    dateOfBirth: "2009-08-22",
    dateRegistered: "2023-10-12",
    gender: "Female",
    status: "Active",
    previousSchoolAttended: "Ikeja Girls School",
    currentClass: {
      name: "Nursery 1",
      division: "Gold",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "AB+",
      genotype: "AC",
      allergies: null,
      medicalHistory: null,
      currentMedications: null,
    },
    address: {
      houseAddress: "369 Oak Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Sophia",
        lastname: "Clark",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Grace",
        lastname: "Clark",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Oyo State",
      lgaOfOrigin: "Ogbomoso LGA",
    },
  },
  {
    id: 23,
    firstname: "Matthew",
    lastname: "Lewis",
    othername: "James",
    abbreviation: "ML",
    username: "CL142345",
    dateOfBirth: "2011-05-30",
    dateRegistered: "2023-11-18",
    gender: "Male",
    status: "Active",
    previousSchoolAttended: "Ikeja Academy",
    currentClass: {
      name: "JSS 2",
      division: "A",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "A+",
      genotype: "AA",
      allergies: null,
      medicalHistory: null,
      currentMedications: null,
    },
    address: {
      houseAddress: "147 Maple Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Matthew",
        lastname: "Lewis",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
    ],
    origin: {
      stateOfOrigin: "Abuja (FCT)",
      lgaOfOrigin: "Kubwa",
    },
  },
  {
    id: 24,
    firstname: "Ava",
    lastname: "Walker",
    othername: "Elizabeth",
    abbreviation: "AW",
    username: "CL143456",
    dateOfBirth: "2007-12-10",
    dateRegistered: "2023-12-25",
    gender: "Female",
    status: "Graduated",
    previousSchoolAttended: "Ikeja International School",
    currentClass: {
      name: "SSS 3",
      division: null,
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "B-",
      genotype: "AA",
      allergies: null,
      medicalHistory: null,
      currentMedications: null,
    },
    address: {
      houseAddress: "258 Spruce Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Ava",
        lastname: "Walker",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Elizabeth",
        lastname: "Walker",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Lagos State",
      lgaOfOrigin: "Itire LGA",
    },
  },
  {
    id: 25,
    firstname: "Lucas",
    lastname: "Robinson",
    othername: "Alexander",
    abbreviation: "LR",
    username: "CL144567",
    dateOfBirth: "2012-03-18",
    dateRegistered: "2024-01-15",
    gender: "Male",
    status: "Graduated",
    previousSchoolAttended: "Ikeja Primary School",
    currentClass: {
      name: "JSS 1",
      division: "B",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "B+",
      genotype: "AA",
      allergies: null,
      medicalHistory: null,
      currentMedications: null,
    },
    address: {
      houseAddress: "369 Cedar Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Lucas",
        lastname: "Robinson",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Alexander",
        lastname: "Robinson",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Kaduna State",
      lgaOfOrigin: "Kabu",
    },
  },
  {
    id: 26,
    firstname: "Isabella",
    lastname: "Martinez",
    othername: "Rose",
    abbreviation: "IM",
    username: "CL145678",
    dateOfBirth: "2008-07-14",
    dateRegistered: "2024-02-20",
    gender: "Female",
    status: "Active",
    previousSchoolAttended: "Ikeja Academy",
    currentClass: {
      name: "SSS 2",
      division: "B",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O-",
      genotype: "AS",
      allergies: null,
      medicalHistory: null,
      currentMedications: null,
    },
    address: {
      houseAddress: "258 Maple Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Isabella",
        lastname: "Martinez",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Rose",
        lastname: "Martinez",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Kano State",
      lgaOfOrigin: "Kumbotso",
    },
  },
  {
    id: 27,
    firstname: "Ethan",
    lastname: "Harris",
    othername: "Michael",
    abbreviation: "EH",
    username: "CL146789",
    dateOfBirth: "2010-09-25",
    dateRegistered: "2024-03-10",
    gender: "Male",
    status: "Active",
    previousSchoolAttended: "Ikeja Secondary School",
    currentClass: {
      name: "JSS 3",
      division: null,
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "A-",
      genotype: "SS",
      allergies: null,
      medicalHistory: ["Sickle cell"],
      currentMedications: null,
    },
    address: {
      houseAddress: "369 Birch Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Ethan",
        lastname: "Harris",
        othername: "Titilola",
        phoneNumber: "08123456789",
        relationship: "Father",
      },
      {
        firstname: "Michael",
        lastname: "Harris",
        othername: "Titilola",
        phoneNumber: "09012345678",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Katsina State",
      lgaOfOrigin: "Dandume",
    },
  },
  {
    id: 28,
    firstname: "Mia",
    lastname: "Thompson",
    othername: "Grace",
    abbreviation: "MT",
    username: "CL147890",
    dateOfBirth: "2009-11-05",
    dateRegistered: "2024-04-15",
    gender: "Female",
    status: "Graduated",
    previousSchoolAttended: "Ikeja Girls School",
    currentClass: {
      name: "SSS 1",
      division: "B",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "B+",
      genotype: "AA",
      allergies: null,
      medicalHistory: null,
      currentMedications: null,
    },
    address: {
      houseAddress: "258 Cedar Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Mia",
        lastname: "Thompson",
        othername: "Grace",
        phoneNumber: "08123456789",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Katsina State",
      lgaOfOrigin: "Charanchi",
    },
  },
  {
    id: 29,
    firstname: "Alexander",
    lastname: "Garcia",
    othername: "James",
    abbreviation: "AG",
    username: "CL148901",
    dateOfBirth: "2011-01-20",
    dateRegistered: "2024-05-25",
    gender: "Male",
    status: "Active",
    previousSchoolAttended: "Ikeja Academy",
    currentClass: {
      name: "JSS 2",
      division: "B",
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "B+",
      genotype: "AA",
      allergies: null,
      medicalHistory: null,
      currentMedications: null,
    },
    address: {
      houseAddress: "258 Maple Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Alexander",
        lastname: "Garcia",
        othername: "James",
        phoneNumber: "08123456789",
        relationship: "Guardian",
      },
    ],
    origin: {
      stateOfOrigin: "Kebbi State",
      lgaOfOrigin: "Arewa Dandi",
    },
  },
  {
    id: 30,
    firstname: "Emily",
    lastname: "Martinez",
    othername: "Elizabeth",
    abbreviation: "EM",
    username: "CL149012",
    dateOfBirth: "2007-03-30",
    dateRegistered: "2024-06-18",
    gender: "Female",
    status: "Active",
    previousSchoolAttended: "Ikeja International School",
    currentClass: {
      name: "SSS 3",
      division: null,
    },
    emergencyContact: {
      name: "Jane Doe",
      phoneNumber: "+123456789",
      relationship: "Mother",
    },
    medicalInformation: {
      bloodType: "O-",
      genotype: "AS",
      allergies: null,
      medicalHistory: null,
      currentMedications: null,
    },
    address: {
      houseAddress: "258 Spruce Street",
      stateOfResidence: "Lagos",
      lgaOfHouse: "Ikeja",
    },
    guardians: [
      {
        firstname: "Emily",
        lastname: "Martinez",
        othername: "Elizabeth",
        phoneNumber: "08123456789",
        relationship: "Mother",
      },
    ],
    origin: {
      stateOfOrigin: "Katsina State",
      lgaOfOrigin: "Keffi",
    },
  },
];
export { students };
